extends: relaxed

rules:
  # Keep things readable while still catching common mistakes.
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  document-start: disable
